In [6]:
import pandas as pd

In [7]:
df1=pd.read_csv("/Users/ameen/Documents/PROJECTS_NEW/Crop/Data/FAOSTAT_data - FAOSTAT_data_en_12-29-2024.csv")

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224647 entries, 0 to 224646
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Domain Code       224647 non-null  object
 1   Domain            224647 non-null  object
 2   Area Code (M49)   224647 non-null  int64
 3   Area              224647 non-null  object
 4   Element Code      224647 non-null  int64
 5   Element           224647 non-null  object
 6   Item Code (CPC)   224642 non-null  object
 7   Item              224647 non-null  object
 8   Year Code         224647 non-null  int64
 9   Year              224647 non-null  int64
 10  Unit              224645 non-null  object
 11  Value             218130 non-null  float64
 12  Flag              224643 non-null  object
 13  Flag Description  224634 non-null  object
 14  Note              5098 non-null    object
dtypes: float64(1), int64(4), object(10)
memory usage: 25.7+ MB

In [9]:
df1.isna().sum()

Domain Code              0
Domain                   0
Area Code (M49)          0
Area                     0
Element Code             0
Element                  0
Item Code (CPC)          5
Item                     0
Year Code                0
Year                     0
Unit                     2
Value                 6517
Flag                     4
Flag Description        13
Note                219549
dtype: int64

In [10]:
df1.fillna(0,inplace=True)

In [11]:
df1.isna().sum()

Domain Code         0
Domain              0
Area Code (M49)     0
Area                0
Element Code        0
Element             0
Item Code (CPC)     0
Item                0
Year Code           0
Year                0
Unit                0
Value               0
Flag                0
Flag Description    0
Note                0
dtype: int64

In [12]:
df1

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,4,Afghanistan,5312,Area harvested,1371,"Almonds, in shell",2019,2019,ha,29203.00,A,Official figure,0
1,QCL,Crops and livestock products,4,Afghanistan,5412,Yield,1371,"Almonds, in shell",2019,2019,kg/ha,1308.30,A,Official figure,0
2,QCL,Crops and livestock products,4,Afghanistan,5510,Production,1371,"Almonds, in shell",2019,2019,t,38205.00,A,Official figure,0
3,QCL,Crops and livestock products,4,Afghanistan,5312,Area harvested,1371,"Almonds, in shell",2020,2020,ha,22134.00,A,Official figure,0
4,QCL,Crops and livestock products,4,Afghanistan,5412,Yield,1371,"Almonds, in shell",2020,2020,kg/ha,1775.90,A,Official figure,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224642,QCL,Crops and livestock products,716,Zimbabwe,5510,Production,22221.01,"Whole milk, evaporated",2019,2019,t,5010.21,I,Imputed value,0
224643,QCL,Crops and livestock products,716,Zimbabwe,5510,Production,22221.01,"Whole milk, evaporated",2020,2020,t,4795.70,I,Imputed value,0
224644,QCL,Crops and livestock products,716,Zimbabwe,5510,Production,22221.01,"Whole milk, evaporated",2021,2021,t,4921.05,I,Imputed value,0
224645,QCL,Crops and livestock products,716,Zimbabwe,5510,Production,22221.01,"Whole milk, evaporated",2022,2022,t,4966.37,I,Imputed value,0
224646,QCL,Crops and livestock products,716,Zimbabwe,5510,Production,24212.02,Wine,2019,2019,t,0.00,A,Official figure,0

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224647 entries, 0 to 224646
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Domain Code       224647 non-null  object
 1   Domain            224647 non-null  object
 2   Area Code (M49)   224647 non-null  int64
 3   Area              224647 non-null  object
 4   Element Code      224647 non-null  int64
 5   Element           224647 non-null  object
 6   Item Code (CPC)   224647 non-null  object
 7   Item              224647 non-null  object
 8   Year Code         224647 non-null  int64
 9   Year              224647 non-null  int64
 10  Unit              224647 non-null  object
 11  Value             224647 non-null  float64
 12  Flag              224647 non-null  object
 13  Flag Description  224647 non-null  object
 14  Note              224647 non-null  object
dtypes: float64(1), int64(4), object(10)
memory usage: 25.7+ MB

In [14]:
df1=df1.drop(['Flag','Flag Description','Year Code','Note','Area Code (M49)','Item Code (CPC)','Element Code'],axis=1)

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224647 entries, 0 to 224646
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Domain Code  224647 non-null  object
 1   Domain       224647 non-null  object
 2   Area         224647 non-null  object
 3   Element      224647 non-null  object
 4   Item         224647 non-null  object
 5   Year         224647 non-null  int64
 6   Unit         224647 non-null  object
 7   Value        224647 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 13.7+ MB

In [16]:
df1=df1.drop(['Domain','Domain Code'],axis=1)

In [17]:
df1.drop_duplicates(inplace=True)

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224647 entries, 0 to 224646
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Area     224647 non-null  object
 1   Element  224647 non-null  object
 2   Item     224647 non-null  object
 3   Year     224647 non-null  int64
 4   Unit     224647 non-null  object
 5   Value    224647 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 10.3+ MB

In [19]:
df1['Element'].unique()

array(['Area harvested', 'Yield', 'Production', 'Stocks',
       'Producing Animals/Slaughtered', 'Laying', 'Yield/Carcass Weight',
       'Milk Animals'], dtype=object)

In [20]:
area_harvested = df1[df1['Element'] == 'Area harvested'].copy()
yield_data= df1[df1['Element'] == 'Yield'].copy()
production = df1[df1['Element'] == 'Production'].copy()

In [21]:
area_harvested

               Area         Element               Item  Year Unit    Value
0       Afghanistan  Area harvested  Almonds, in shell  2019   ha  29203.0
3       Afghanistan  Area harvested  Almonds, in shell  2020   ha  22134.0
6       Afghanistan  Area harvested  Almonds, in shell  2021   ha  36862.0
9       Afghanistan  Area harvested  Almonds, in shell  2022   ha  36462.0
12      Afghanistan  Area harvested  Almonds, in shell  2023   ha  37000.0
...             ...             ...                ...   ...  ...      ...
224619     Zimbabwe  Area harvested              Wheat  2019   ha  24186.0
224622     Zimbabwe  Area harvested              Wheat  2020   ha  44466.0
224625     Zimbabwe  Area harvested              Wheat  2021   ha  66434.0
224628     Zimbabwe  Area harvested              Wheat  2022   ha  48504.0
224631     Zimbabwe  Area harvested              Wheat  2023   ha  65878.0

[50309 rows x 6 columns]

In [22]:
yield_data

               Area Element               Item  Year   Unit   Value
1       Afghanistan   Yield  Almonds, in shell  2019  kg/ha  1308.3
4       Afghanistan   Yield  Almonds, in shell  2020  kg/ha  1775.9
7       Afghanistan   Yield  Almonds, in shell  2021  kg/ha  1743.2
10      Afghanistan   Yield  Almonds, in shell  2022  kg/ha  1742.0
13      Afghanistan   Yield  Almonds, in shell  2023  kg/ha  1810.8
...             ...     ...                ...   ...    ...     ...
224620     Zimbabwe   Yield              Wheat  2019  kg/ha  3914.9
224623     Zimbabwe   Yield              Wheat  2020  kg/ha  4779.6
224626     Zimbabwe   Yield              Wheat  2021  kg/ha  5075.9
224629     Zimbabwe   Yield              Wheat  2022  kg/ha  5154.2
224632     Zimbabwe   Yield              Wheat  2023  kg/ha  4553.8

[51566 rows x 6 columns]

In [23]:
production

               Area     Element                    Item  Year Unit     Value
2       Afghanistan  Production       Almonds, in shell  2019    t  38205.00
5       Afghanistan  Production       Almonds, in shell  2020    t  39307.00
8       Afghanistan  Production       Almonds, in shell  2021    t  64256.00
11      Afghanistan  Production       Almonds, in shell  2022    t  63515.00
14      Afghanistan  Production       Almonds, in shell  2023    t  67000.00
...             ...         ...                     ...   ...  ...       ...
224642     Zimbabwe  Production  Whole milk, evaporated  2019    t   5010.21
224643     Zimbabwe  Production  Whole milk, evaporated  2020    t   4795.70
224644     Zimbabwe  Production  Whole milk, evaporated  2021    t   4921.05
224645     Zimbabwe  Production  Whole milk, evaporated  2022    t   4966.37
224646     Zimbabwe  Production                    Wine  2019    t      0.00

[86382 rows x 6 columns]

In [24]:
df_main=pd.merge(area_harvested[['Area', 'Item', 'Year', 'Value']].rename(columns={'Value': 'Area_harvested'}),
                yield_data[['Area', 'Item', 'Year', 'Value']].rename(columns={'Value': 'Yield'}),
                on=['Area', 'Item', 'Year'],
                how='inner'
            )

In [25]:
df_main= pd.merge(
                df_main,
                production[['Area', 'Item', 'Year', 'Value']].rename(columns={'Value': 'Production'}),
                on=['Area', 'Item', 'Year'],
                how='inner'
            )

In [26]:
df_main

,Area,Item,Year,Area_harvested,Yield,Production
0,Afghanistan,"Almonds, in shell",2019,29203.0,1308.3,38205.0
1,Afghanistan,"Almonds, in shell",2020,22134.0,1775.9,39307.0
2,Afghanistan,"Almonds, in shell",2021,36862.0,1743.2,64256.0
3,Afghanistan,"Almonds, in shell",2022,36462.0,1742.0,63515.0
4,Afghanistan,"Almonds, in shell",2023,37000.0,1810.8,67000.0
...,...,...,...,...,...,...
44976,Zimbabwe,Wheat,2019,24186.0,3914.9,94685.0
44977,Zimbabwe,Wheat,2020,44466.0,4779.6,212530.0
44978,Zimbabwe,Wheat,2021,66434.0,5075.9,337212.0
44979,Zimbabwe,Wheat,2022,48504.0,5154.2,250000.0
44980,Zimbabwe,Wheat,2023,65878.0,4553.8,300000.0

In [27]:
df_main.isna().sum()

Area              0
Item              0
Year              0
Area_harvested    0
Yield             0
Production        0
dtype: int64

In [28]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44981 entries, 0 to 44980
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Area            44981 non-null  object
 1   Item            44981 non-null  object
 2   Year            44981 non-null  int64
 3   Area_harvested  44981 non-null  float64
 4   Yield           44981 non-null  float64
 5   Production      44981 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.1+ MB

>Feature preparation

In [57]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import  r2_score, accuracy_score, mean_absolute_error, mean_squared_error

In [30]:
enc_area=LabelEncoder()
enc_item=LabelEncoder()

In [31]:
feature_names = ['Area_encoded', 'Item_encoded', 'Year', 'Area_harvested', 'Yield']

In [32]:
df_main['Area_encoded'] = enc_area.fit_transform(df_main['Area'])
df_main['Item_encoded'] = enc_item.fit_transform(df_main['Item'])

In [40]:
path1="/Users/ameen/Documents/PROJECTS_NEW/Crop/Data/cleaned_data.csv"
df_main.to_csv(path1,index=False)

In [33]:

X = pd.DataFrame(df_main[feature_names])
y = df_main['Production']

>Train moodel

In [37]:
model = RandomForestRegressor(
                n_estimators=200,  
                max_depth=20,      
                min_samples_split=5,
                min_samples_leaf=2,
                n_jobs=-1  
            )

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [39]:
model.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, min_samples_leaf=2, min_samples_split=5,
                      n_estimators=200, n_jobs=-1)

In [41]:
pred = model.predict(X_test)

>Metrics

In [58]:

r2_score = r2_score(y_test, pred)
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
CV_scores = cross_val_score(model, X, y, cv=5)

In [51]:
print("r2_score",r2_score)
print("Mean squared error",mse)
print("root mean squared error",rmse)
print('cross validation score',CV_scores)

r2_score 0.9965870024290572
Mean squared error 198031473573.1631
root mean squared error 445007.2736182669
cross validation score [0.87570613 0.98099509 0.65802071 0.96887523 0.91185239]

In [59]:
import joblib 
file_name = 'crop_pred.pkl' 
joblib.dump(model, file_name)

['crop_pred.pkl']